import "@/app/styles/styles.scss";
import { AuthProvider } from "./Providers";

export const metadata = {
  title: "(MCQ) Exams | OLI Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <AuthProvider>
        {children}
        </AuthProvider>
        </body>
    </html>
  );
}
